### ISSUE TITLE
Kostenberechnung

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Verteilte-DB#1]
Wie setzt man die unterschiedlichen Preise für Ausleihen in Tagen, Wochen oder Monaten um?

**Comment by mbasti** [comment]
Ich weiß nicht wie das Kostenmodell ist. Kann man nicht einfach die Tage zwischen rentFrom und rentTo brechnen und mit dem Tagespreis multiplizieren? Warum gibt es Tages-,Wochen-,Monatspreis?

**Comment by autarchprinceps** [comment]
Ich glaube ich habe einen Ansatz:
           count(id) \* tagespreis \* in_tagen(rentto - rentfrom) where rentto - rentfrom < 7 Tage
PLUS  count(id) \* wochenpreis \* in_wochen(rentto - rentfrom) where rentto - rentfrom < 30 Tage and rentto - rentfrom > 7 tage
PLUS count(id) \* monatspreis \* in_monaten(rentto - rentfrom) where rentto - rentfrom > 30 tage
Könnte einer von euch das in SQL ausformulieren? Aber vom Prinzip müsste das doch stimmen, oder?

Die Idee der Preise ist, dass umso länger man etwas mietet, umso kleiner sollten die Kosten pro Zeit sein. Das ist häufig so, aber das hier ist eine ziemlich schlechte Art das in SQL darzustellen. Aber das ist wohl kaum das einzige, was an dem gegebenen Schema ziemlich behindert geregelt ist.
