### ISSUE TITLE
vor ü2:

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Verteilte-DB#2]
da ihr glaub ich nicht da wart, wichtige infos heute:
- für nächste übungen weiter mit gleichem schema, aber ohne vertikale fragmentierung
  - ohne vertikale fragmentierung, wo packen wir die supplier hin? bleiben wir bei "resupply nur von bonn aus"?
- lokale präfixe (anders als bei unserem schema)

**Comment by autarchprinceps** [comment]
möglichkeiten:
- repliziert an allen standorten
- nur an einem (z.b. bonn)
- horizontal fragmentiert:
  - welches prädikat? state ist bei allen beispieldaten deutschland und ein supplier kann potenziell ja auch an mehrere standorte liefern

**Comment by autarchprinceps** [comment]
ü2 ist übrigens bis diesen so zu erledigen!

**Comment by mbasti** [comment]
meinentwegen können wir bei "resupply nur von bonn" bleiben und alles in Bonn speichern. In der Übung steht, dass wir noch keine Replikation machen sollen.
