### ISSUE TITLE
u3

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Verteilte-DB#3]
Ich habe die SQL-Dateien erstellt und getestet und die Fragen soweit beantwortet, wie ich im Moment komme. Ich bin mir bei ein paar Sachen nicht sicher. Vielleicht könnt ihr über die Fragen.md drübergucken und Ergänzungen hinzufügen, wo mir nicht genug eingefallen ist.

@MBasti Bist du krank/verhindert, oder hast du keine Lust mehr zu den Vorlesungen zu kommen?

**Comment by mbasti** [comment]
@autarchprinceps beides. Ne im Ernst, ich war die letzten Tage krank.

**Comment by autarchprinceps** [comment]
@MBasti Gute Besserung. Du hast, zumindest in den Vorlesungen, die wir beide besuchen, nichts verpasst, was nicht auch in den Skripten steht.

**Comment by mbasti** [comment]
@autarchprinceps Ok danke. Habt ihr schon die Vorlesung zu Transaktionen gemacht?
- a) ii Muss nicht nur das Schema aktuell gehalten werden, sondern auch die Daten bei jedem Insert, Update,..., was auf den darunter liegenden Tabellen ausgeführt wird, wodurch jedes mal Traffic entsteht? Die Views müssen lokal doch immer aktuell gehalten werden, oder? Mal abgesehen davon, dass bei der Beispielanwendung nicht viel passiert.

**Comment by autarchprinceps** [comment]
In Views kann mein kein Insert oder Update machen und lesende Zugriffe werden meines Wissens immer an die Tabellen weitergeleitet. Wenn man also einen View aus den Tabellen mehrerer DBs macht, dann werden neue Daten in den entfernten DBs auch automatisch im View sichtbar (höchstens Verzögerung durch Cache oder so).
Aber wenn man die Views auf allen DBs separat anlegt, müssen sie auch auf allen DBs separat geändert werden. Wenn man sie nur auf einer DB anlegt und von den anderen DBs darauf verweist, müssen sie nur dort geändert werden, aber wenn man sie nicht ändert, sondern nur immer wieder selects macht, muss, da der View ja nur in der anderen DB angelegt wurde, die andere DB immer wieder gefragt werden, wie der View aussieht (ob er sich geändert hat ...).

Wir haben ein bisschen Transaktionen gemacht. Ich habe nicht immer ganz genau zugehört, aber es war so gut wie alles Wdh. ACID und dessen Umsetzung in relationalen DBs. Ich glaube nicht, dass wir schon wirklich was zu verteilten Transaktionen gemacht haben.
