### ISSUE TITLE
u4 - a3

### ISSUE THREAD

**Issue by alex-laitenberger** [autarchprinceps/Verteilte-DB#4]
@autarchprinceps, @MBasti 
Moin Männers!

ich hab ein kleines Prob bei Aufgabe 3 - Wir sollen Trigger setzen für INSERT und DELETE Operationen auf der globalen View.. 

Ich habe das mal zuerst mit der Customer View probiert:
Bei mir zeigt er Fehler an "Tabelle oder View nicht vorhanden".
Ich gehe davon aus, dass er damit diese Wert Abfragen in den IF-Statements meint (:new.state = '')
Habt ihr ne Ahnung, wie man auf die Attribute des einzufügenden Wertes sonst zugreifen kann?

**Comment by alex-laitenberger** [comment]
in Zeile 104 btw..

**Comment by mbasti** [comment]
ändere mal **LND**_CUSTOMER@london zu **LDN**_CUSTOMER ...

**Comment by alex-laitenberger** [comment]
Dann kommen noch mehr Fehler :-/

Was ist denn mit dem if :new.state='' - kann man das iwie anders abfragen?

**Comment by alex-laitenberger** [comment]
Moment falsch gelesen :-)) ich check das mal

**Comment by mbasti** [comment]
Hm also ich kann das Ding kompilieren. Löschst du den Trigger vorher? Also das @london kannst du drin lassen (LDN_CUSTOMER@london)

**Comment by alex-laitenberger** [comment]
danke, das wars! :dancer:

**Comment by alex-laitenberger** [comment]
nächste Frage: habt ihr ne Idee wie wir für die View ARTICLE in der If-Abfrage auf die abhängige Tabelle DEPOT zugreifen? die Fragmentierung hängt ja bei Article vom State des referenzierten Depot-Eintrags ab... Hab mal meinen Stand zu Bonn gepusht..

**Comment by autarchprinceps** [comment]
die tabelle depot ist an anderen standorten als bonn über ein synonym ebenfalls vorhanden.

**Comment by autarchprinceps** [comment]
oder meinst du wie man überhaupt auf andere tabellen zugreift?

**Comment by autarchprinceps** [comment]
Wie sollen die IDs an den anderen Standorten generiert werden? Bis jetzt ist das ja noch nicht implementiert.

Ich habe nachgeguckt, es wäre möglich ein Synonym auf eine zentrale Sequenz zu erstellen. Alternativ könnte man den Bereich möglicher IDs im vorhinein aufspalten, oder?
Gleiches gilt glaub ich für die Trigger. Ein Insert, Update oder Delete muss ja von jedem Standort für alle Daten transparent erfolgen.
Wenn wir an jedem Standort eine Sequenz haben, dann kann auch der globale Trigger an jedem Standort ausgeführt werden, oder wir lassen alle globale Trigger zentral laufen.
Die Konsequenzen sind dieselben wie auch schon bei der Entscheidung von replizierten Views oder Synonymen auf zentrale Views.

Oder übersehe ich dabei irgendwas wichtiges?

**Comment by mbasti** [comment]
Also wenn das wirklich geht mit der zentralen Sequenz, dann spricht doch nichts dagegen, oder? Wäre auch bei einer theoretischer Migration besser, weil man dann nicht die Schlüssel anpassen muss wie bei aufgeteilten Schlüsselbereichen.

**Comment by mbasti** [comment]
@alex-ellpunkt im letzten Commit für Bonn habe ich das gemacht, was du meinst (glaube ich).

**Comment by autarchprinceps** [comment]
Was ist eigentlich mit Updates von State?
Ich meine, da wir delete abhängig von state im global trigger machen, bräuchten wir ja eigentlich eine move, wenn man update von state macht.
Sorry für das Denglish.

**Comment by alex-laitenberger** [comment]
hey. cool Basti, genau das hatte mir gefehlt :+1: 

 also ich hab ursprünglich geplant, bonn ne sequenz von 100000 - 199999 zu verpassen, london 200000 - 299999 und nyk 3... - 3...

Wenn Du das mit ner zentralen Sequenz umsetzen kannst, wäre das natürlich auch cool Patrick. Willst du das machen? Dann sollten wir relativ zügig den Rest implementieren, haben ja nur noch 4h :fire_engine:

**Comment by alex-laitenberger** [comment]
also ich implementier das jetzt erstmal so mit den sequenzen, wenn ihr´s später zentral machen wollt, tut euch keinen Zwang an..

**Comment by alex-laitenberger** [comment]
ok, wollt´s gerade commiten und seh, dass du´s jetzt mit zentralen sequenzen und Synonymen gemacht hast :+1:

**Comment by autarchprinceps** [comment]
Sorry, hatte deinen Post nicht gesehen. Ich habe es mal so gemacht, läuft so weit ich das sehen kann alles.
