### ISSUE TITLE
U5

### ISSUE THREAD

**Issue by alex-laitenberger** [autarchprinceps/Verteilte-DB#5]
Moin. Hab grad versucht den bisherigen Entwurf zu kompilieren, aber bekomme lauter Fehlermeldungen. Erst war ein Statement zu lang, als ich´s gekürzt habe, hatte plötzlich sämtliche Trigger irgendwelche Compiler Fehler.. 
Ist das bei euch auch so ?

**Comment by alex-laitenberger** [comment]
@autarchprinceps 
@MBasti

**Comment by autarchprinceps** [comment]
Habs bis jetzt noch nicht ausprobiert, kannst du den Fehler etwas genauer beschreiben? Welches Statement ist zu lang? Und was soll zu lang eigentlich heißen, gibt es eine Größenbeschränkung in PL/SQL?

**Comment by autarchprinceps** [comment]
Ist gefixed. Strings in SQL müssen mit ' und nicht mit " eingegrenzt werden, deshalb hat er unsere Fehlermeldungen als Bezeichner verwenden wollen.
Jetzt brauchen wir nur noch ein paar geignete Testfälle, welche die funktionieren sollten und welche die nicht funktionieren sollten.
